repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
    -   id: mixed-line-ending
    -   id: trailing-whitespace

-   repo: https://github.com/ikamensh/flynt/
    rev: '0.63'
    hooks:
    -   id: flynt
        args: [
            '--line-length=120',
            '--fail-on-change',
        ]

-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.31.0
    hooks:
    -   id: yapf
        name: yapf
        types: [python]
        args: ['-i']
        additional_dependencies: ['toml']
        exclude: &exclude_files >
            (?x)^(
                docs/.*|
                tests/.*|
            )$

-   repo: https://github.com/PyCQA/pylint
    rev: v2.8.2
    hooks:
    -   id: pylint
        language: system
        exclude: *exclude_files
